name: Set up EKS With Terraform

on: push 

jobs: 

  LogInToAWS:
    runs-on: ubuntu-latest 

    steps:
    - name: Configure credentials 
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} 
        
  TerraformInit:
    runs-on: ubuntu-latest
    needs: LogInToAWS

    steps:
    - name: Checkout 
      uses: actions/checkout@v4 

    - name: Initialize Terraform 
      run: |
        terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
  
  TerraformPlan:
    runs-on: ubuntu-latest 
    needs: TerraformInit

    steps: 
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Plan Terraform
      run: | 
        terraform plan
      env:  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

  TerraformValidate:
    runs-on: ubuntu-latest 
    needs: TerraformPlan

    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Validate Terraform 
      run: |
        terraform validate 
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }} 
  
  TerraformApply:
    runs-on: ubuntu-latest 
    needs: TerraformValidate

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Plan Terraform 
      run: |
        terraform apply 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}



        
