name: Set up EKS With Terraform

on: push 

jobs: 

  LogInToAWS:
    runs-on: ubuntu-latest 

    steps:
    - name: Configure credentials 
      uses: aws-actions/configure-aws-credentials@v4 
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} 
        
  TerraformInit:
    runs-on: ubuntu-latest
    needs: LogInToAWS

    steps:
    - name: Checkout 
      uses: actions/checkout@v4 

    - name: Initialize Terraform 
      run: |
        terraform init

        
